version: 2.1

executors:
  ruby:
    parameters:
      ruby-version:
        type: string
        default: "2.6"
      gemfile:
        type: string
        default: "Gemfile"
    docker:
      - image: circleci/ruby:<< parameters.ruby-version >>
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          BUNDLE_GEMFILE: << parameters.gemfile >>

jobs:
  test:
    parameters:
      ruby-version:
        type: string
    executor:
      name: ruby
      ruby-version: << parameters.ruby-version >>
    parallelism: 1
    steps:
      - checkout

      - run:
          # Remove the non-appraisal gemfile for safety: we never want to use it.
          name: Prepare bundler
          command: bundle -v

      - run:
          name: Compute a gemfile lock
          command: bundle lock && cp "${BUNDLE_GEMFILE}.lock" /tmp/gem-lock

      - restore_cache:
          keys:
            - phraseapp_updater-v2-<< parameters.ruby-version >>-{{ checksum "/tmp/gem-lock" }}
            - phraseapp_updater-v2

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: phraseapp_updater-v2-<< parameters.ruby-version >>-{{ checksum "/tmp/gem-lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run rspec
          command: bundle exec rspec --profile 10 --format RspecJunitFormatter --out test_results/rspec.xml --format progress

      - store_test_results:
          path: test_results

  publish:
    executor: ruby
    steps:
       - checkout
       - run:
           name: Setup Rubygems
           command: |
             mkdir ~/.gem &&
             echo -e "---\r\n:rubygems_api_key: $RUBYGEMS_API_KEY" > ~/.gem/credentials &&
             chmod 0600 ~/.gem/credentials
       - run:
           name: Publish to Rubygems
           command: |
             gem build phraseapp_updater.gemspec
             gem push phraseapp_updater-*.gem


workflows:
  version: 2.1
  build:
    jobs:
      - test:
          name: 'ruby 2.5'
          ruby-version: "2.5"
      - test:
          name: 'ruby 2.6'
          ruby-version: "2.6"
      - publish:
          requires:
            - 'ruby 2.5'
            - 'ruby 2.6'
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
